[package]
name = "rusty2048-shared"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Shared components for Rusty2048"
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
